on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build and Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Start LocalStack
      run: |
        pip install localstack
        docker pull localstack/localstack
        localstack start -d

    - name: Deploy app and run test
      run: make test
